summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-linux-riscv64/releases/download/2024.08.16/pkg-config-0.29.2-linux-riscv64.tar.xz
bin-sha: 400924da87620732e0e05375da84973f975a537ea4f86be139d453d781f77731
