summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-linux-riscv64/releases/download/2025.06.06/pkg-config-0.29.2-linux-riscv64.release.tar.xz
bin-sha: 4f491f14f90fafa3cb3517bcb1ded3a141810eec22a20342605d59025a2e7434
